import type { AiraConfig, CommandDefinition } from "../types/config.js";
import { DEFAULT_COMMANDS } from "../types/config.js";

/**
 * Renders the generated CLI's `bin/index.js`. The output is a small,
 * self-contained Node script (no build step needed at runtime) that:
 *   - defines Commander commands from the config
 *   - calls the developer's AI API via the shared @aira/runtime helpers
 *   - renders responses with the chosen theme (gradient logo, markdown, etc.)
 *
 * Keeping generated CLIs as plain JS (not requiring Aira itself as a runtime
 * dependency beyond @aira/runtime) is what makes them lightweight to publish
 * and fast to install via npx.
 */
export function renderCliEntry(config: AiraConfig): string {
  const commands = config.commands?.length ? config.commands : DEFAULT_COMMANDS;
  const cliName = config.name;

  const commandBlocks = commands.map((cmd) => renderCommandBlock(cmd)).join("\n\n");

  return `#!/usr/bin/env node
/**
 * ${config.displayName ?? cliName} — generated by Aira CLI Kit.
 * Do not edit directly if you plan to re-run \`aira build\`; edit aira.config.json instead.
 */
import { Command } from "commander";
import {
  printBanner,
  runApiCommand,
  startChatRepl,
  loadRuntimeConfig,
  doctorCheck,
} from "@aira/runtime";

const config = loadRuntimeConfig(import.meta.url);
const program = new Command();

program
  .name("${cliName}")
  .description(${JSON.stringify(config.description ?? `${cliName} — AI-powered CLI`)})
  .version(${JSON.stringify(config.version ?? "0.1.0")});

program
  .command("doctor")
  .description("Check environment, auth and connectivity")
  .action(() => doctorCheck(config));

${commandBlocks}

if (process.argv.length <= 2) {
  printBanner(config);
  program.outputHelp();
} else {
  program.parse();
}
`;
}

function renderCommandBlock(cmd: CommandDefinition): string {
  const flags = (cmd.params ?? [])
    .map((p) => `  .option(${JSON.stringify(p.flag)}, ${JSON.stringify(p.description)}${p.default !== undefined ? `, ${JSON.stringify(p.default)}` : ""})`)
    .join("\n");

  if (cmd.interactive) {
    return `program
  .command("${cmd.name}")
  .description(${JSON.stringify(cmd.description)})
${flags}
  .action((opts) => startChatRepl(config, ${JSON.stringify(cmd)}, opts));`;
  }

  return `program
  .command("${cmd.name} <input>")
  .description(${JSON.stringify(cmd.description)})
${flags}
  .action((input, opts) => runApiCommand(config, ${JSON.stringify(cmd)}, input, opts));`;
}
