import { mkdirSync, writeFileSync, chmodSync } from "node:fs";
import { join } from "node:path";
import type { AiraConfig } from "../types/config.js";
import { renderCliEntry } from "../templates/cliEntry.template.js";
import { renderPackageJson } from "../templates/packageJson.template.js";
import { renderReadme } from "../templates/readme.template.js";
import { renderGithubWorkflow } from "../templates/githubWorkflow.template.js";
import { renderDockerfile } from "../templates/dockerfile.template.js";
import { logger } from "../core/logger.js";
import { loadPlugins } from "../plugins/pluginManager.js";

export interface BuildResult {
  outDir: string;
  files: string[];
}

/**
 * Generates a complete, publishable CLI project on disk from a single AiraConfig.
 * This is what `aira build` (and `aira dev` under the hood) calls.
 */
export async function buildCli(config: AiraConfig): Promise<BuildResult> {
  const outDir = join(process.cwd(), config.outDir ?? `dist-cli/${config.name}`);
  const binDir = join(outDir, "bin");
  const files: string[] = [];

  mkdirSync(binDir, { recursive: true });

  // Resolve plugins up front so build fails fast on a missing/broken plugin.
  const plugins = await loadPlugins(config.plugins ?? []);
  for (const plugin of plugins) {
    plugin.onBuild?.(config);
  }

  const entryPath = join(binDir, "index.js");
  writeFileSync(entryPath, renderCliEntry(config), "utf-8");
  chmodSync(entryPath, 0o755);
  files.push(entryPath);

  // Baked-in runtime config: lets the generated CLI run standalone without
  // needing aira.config.json or Aira itself present at runtime.
  const runtimeConfigPath = join(binDir, "aira.runtime.json");
  writeFileSync(runtimeConfigPath, JSON.stringify(config, null, 2), "utf-8");
  files.push(runtimeConfigPath);

  const pkgPath = join(outDir, "package.json");
  writeFileSync(pkgPath, renderPackageJson(config), "utf-8");
  files.push(pkgPath);

  const readmePath = join(outDir, "README.md");
  writeFileSync(readmePath, renderReadme(config), "utf-8");
  files.push(readmePath);

  const workflowDir = join(outDir, ".github", "workflows");
  mkdirSync(workflowDir, { recursive: true });
  const workflowPath = join(workflowDir, "release.yml");
  writeFileSync(workflowPath, renderGithubWorkflow(config), "utf-8");
  files.push(workflowPath);

  const dockerfilePath = join(outDir, "Dockerfile");
  writeFileSync(dockerfilePath, renderDockerfile(config), "utf-8");
  files.push(dockerfilePath);

  const licensePath = join(outDir, "LICENSE");
  writeFileSync(licensePath, "MIT License\n\nGenerated by Aira CLI Kit.\n", "utf-8");
  files.push(licensePath);

  logger.success(`Generated CLI "${config.name}" → ${outDir}`);
  return { outDir, files };
}
